# Generated by Django 4.1.3 on 2023-05-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompraSometida', '0003_alter_comprasometida_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasometida',
            name='num_reporte',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
