# Generated by Django 4.1.3 on 2023-05-15 03:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia_id', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('acronimo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('categoria', models.CharField(choices=[('DEL', 'Delegada'), ('EXE', 'Exenta')], default=('', ''), max_length=30)),
                ('tipo', models.CharField(default='', max_length=1000)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('image_agencia', models.ImageField(upload_to='agencia')),
                ('alerta', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
