# Generated by Django 4.1.3 on 2023-05-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agencias', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='acronimo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='alerta',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agencia',
            name='nombre',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
