# Generated by Django 4.1.3 on 2023-05-15 03:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casos', '0001_initial'),
        ('Agencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id_infraccion', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('aviso', models.IntegerField()),
                ('primera_multa', models.IntegerField()),
                ('segunda_multa', models.IntegerField()),
                ('tercera_multa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MultasAprobada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multa_id', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('total', models.CharField(max_length=60)),
                ('pago', models.BooleanField(blank=True, null=True)),
                ('infraccion_count', models.IntegerField(default=0)),
                ('infraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Multas.infraccion')),
                ('nombre_agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencias.agencia')),
                ('num_caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casos.caso')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multa_id', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('total', models.CharField(max_length=60)),
                ('pago', models.BooleanField(blank=True, null=True)),
                ('infraccion_count', models.IntegerField(default=0)),
                ('infraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Multas.infraccion')),
                ('nombre_agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencias.agencia')),
                ('num_caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Casos.caso')),
            ],
        ),
    ]
