# Generated by Django 4.1.3 on 2023-05-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0002_alter_compra_asignacion_alter_compra_concepto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='num_licitador',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='procedencia',
            field=models.CharField(choices=[('PR', 'PR'), ('USA', 'USA'), ('EXT', 'EXT')], default=('', ''), max_length=1000),
        ),
    ]
