# Generated by Django 4.1.3 on 2023-05-15 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0003_alter_compra_fecha_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_reporte',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='compra',
            name='fondos',
            field=models.CharField(choices=[('Estatal', 'Estatal'), ('Federal', 'Federal'), ('Ingresos Propios', 'Ingresos Propios')], default=('', ''), max_length=1000),
        ),
    ]
