# Generated by Django 4.1.3 on 2023-05-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0004_alter_compra_fondos'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='num_reporte',
            field=models.IntegerField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='concepto',
            field=models.CharField(choices=[('1', 'Nomina'), ('2', 'Facilidades y Servicios Publicos'), ('3', 'Servicios Comprados'), ('4', 'Donativos y Subsidios'), ('5', 'Gastos de Transportacion y Substinencia'), ('6', 'Servicios Profesionales'), ('7', 'Otros Gastos'), ('8', 'Inversion en Mejoras Permanentes'), ('9', 'Amortizacion de la Deuda'), ('10', 'Materiales y Suministros'), ('11', 'Compra de Equipo'), ('12', 'Anuncios y Pautas en Medios'), ('13', 'Incentivos y Subsidios Bienestar Ciudadano'), ('14', 'Aportaciones a Entidades No Gubernamentales'), ('81', 'Asignaciones Englobadas'), ('82', 'Pareo Fondos Federales'), ('89', 'Deudas de Años Anteriores')], default=('-', '-'), max_length=1000),
        ),
    ]
