# Generated by Django 4.1.3 on 2023-05-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0005_compra_num_reporte_alter_compra_concepto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='num_reporte',
            field=models.IntegerField(null=True),
        ),
    ]
