# Generated by Django 4.1.3 on 2023-05-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0006_alter_compra_num_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='num_reporte',
        ),
    ]
