# Generated by Django 4.1.3 on 2023-05-12 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agencias', '0003_alter_agencia_acronimo_alter_agencia_alerta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Compras', '0007_remove_compra_num_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id_agencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agencias.agencia'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_comprador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
